### PR TITLE
[12.0][FIX] search backend by api key name

### PR DESCRIPTION
**Pull request by sbidoul**
Use filtered to search because `auth_api_key_name` is not searchable.

### CODE REVIEW

**Review by lmignon — APPROVED** [review]

**Comment by lmignon** [comment]
@sbidoul pre-commit fails. Can you fix the code?

**Comment by sbidoul** [comment]
@lmignon done

**Review by simahawk — APPROVED** [review]

**Comment by simahawk** [comment]
seems to fail [here](https://travis-ci.org/shopinvader/odoo-shopinvader/jobs/570855106#L2522) ` AttributeError: module 'botocore.awsrequest' has no attribute 'AWSHTTPConnectionPool'`

**Comment by sbidoul** [comment]
Trying if https://github.com/akretion/storage/pull/84 fixes it.

**Pull request merged**
