### PR TITLE
[14.0][MIG] shopinvader_membership

### PR DESCRIPTION
**Pull request by acsonefho**
Migration of module `shopinvader_membership` from `10.0` to `14.0`

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review.

@acsonefho Are all last commits significant ?

**Review by lmignon — CHANGES_REQUESTED** [review]
@acsonefho Why does this addon depend on shopinvader? It's just an api on top of membeship.  IMO it should not depend on shopinvader.  FYI base_rest will provide a unified way to access to the authenticated_partner_id (see https://github.com/OCA/rest-framework/pull/204 and https://docs.google.com/document/d/1fNCWMU7iSXoniUjl42sdPOO-OcNpKZuMaT-dg6-PpIY)

**Comment by rousseldenis** [comment]
> @acsonefho Why does this addon depend on shopinvader? It's just an api on top of membeship. IMO it should not depend on shopinvader. FYI base_rest will provide a unified way to access to the authenticated_partner_id (see [OCA/rest-framework#204](https://github.com/OCA/rest-framework/pull/204) and https://docs.google.com/document/d/1fNCWMU7iSXoniUjl42sdPOO-OcNpKZuMaT-dg6-PpIY)

@lmignon Because memberships will be used in customer profile page on frontend.

**Comment by lmignon** [comment]
By reading the code I see that in this case you are selling specific products. Therefore, my comment is not valid.

**Review by lmignon — APPROVED** [review]

**Pull request merged**
