### PR TITLE
[14.0][ADD] shopinvader_product_order

### PR DESCRIPTION
**Pull request by ivantodorovich**
Module to manage the display order of products in the shop

### CODE REVIEW

**Review by simahawk — COMMENTED** [review]
LG

**Comment by kevinkhao** [comment]
nitpicking and non-blocking: maybe shopinvader_product_sequence or is better for avoiding confusion with purchase orders

**Comment by ivantodorovich** [comment]
> nitpicking and non-blocking: maybe shopinvader_product_sequence or is better for avoiding confusion with purchase orders

I considered it but it may suggest the use of `ir.sequence` (for example [this module](https://github.com/OCA/product-attribute/tree/14.0/product_sequence) or [this one](https://github.com/OCA/partner-contact/tree/14.0/base_partner_sequence)) :sweat_smile:

**Review by simahawk — APPROVED** [review]

**Review by sebastienbeau — APPROVED** [review]
LGTM code review

**Pull request merged**
