### PR TITLE
[13.0] Add shopinvader_product_variant_multi_link

### PR DESCRIPTION
**Pull request by simahawk**
- [x] Depends on https://github.com/OCA/e-commerce/pull/429

Regarding the change on s_product_template_multi_link, before this change for every link type you had to add a new computed field and a new key to the index.

Now the index data is flexible and contains a mapping by link type.

Finally it's easier now to override the behavior of every part of the
computation, included the data generated per each link type.

**:warning: WARNING: the data in the indexes will change.**

Before you had `cross_selling` `up_selling` as main keys.
Now you have `links.cross_selling`, `links.up_selling`, `links.$whatever_link_type_code_you_add`.

CC @lmignon

### CODE REVIEW

**Comment by simahawk** [comment]
I need to fix grouping by type and specific link data.

**Comment by lmignon** [comment]
looks promising :heart_eyes:

**Comment by simahawk** [comment]
@lmignon beside the flag `_product_variant_link_bypass_check` to be removed in the base module, I think is ready for review :wink:

**Review by lmignon — APPROVED** [review]
Even if I prefer to have on py file by class https://github.com/shopinvader/odoo-shopinvader/pull/776/files#diff-51edb191b6da9662d03aab990ebdccf9R15 :smirk: LGTM :+1:

**Review by guewen — APPROVED** [review]

**Pull request merged**
