### PR TITLE
[MIG] shopinvader_import_image: Migration to 13.0

### PR DESCRIPTION
**Pull request by simahawk**
Depends on https://github.com/OCA/storage/pull/34 + https://github.com/shopinvader/odoo-shopinvader/pull/552

Migrated and refactored.
I'll add support to read from external storage via storage_backend.

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by simahawk** [comment]
I merge as it is since it works. I add some improvements in another PR

**Comment by simahawk** [comment]
hmm I cancelled the build. I just realized I messed up some commits :sob:

**Pull request merged**
