### PR TITLE
[REF] remove all @job to use the new api

### PR DESCRIPTION
**Pull request by sebastienbeau**

### CODE REVIEW

**Review by PierrickBrun — APPROVED** [review]

**Comment by simahawk** [comment]
@PierrickBrun can you rebase instead of merge?

**Comment by PierrickBrun** [comment]
> @PierrickBrun can you rebase instead of merge?

Indeed, I'll wait for https://github.com/shopinvader/odoo-shopinvader/pull/823/commits/59ef5cc0771850fc5775f3c15cbc0717924ff478 to be sorted then I'll rebase

**Review by ThomasBinsfeld — APPROVED** [review]

**Pull request merged**
