### PR TITLE
[IMP] add carrier code into api response

### PR DESCRIPTION
**Pull request by sebastienbeau**

### CODE REVIEW

**Comment by sebastienbeau** [comment]
regarding port forwarding on 12 I think we miss this commit https://github.com/shopinvader/odoo-shopinvader/commit/5daa01ed182e916ea46325772e00bc78b51b0017

**Review by rousseldenis — APPROVED** [review]
@sebastienbeau Do you plan to integrate this in tests?

**Comment by rousseldenis** [comment]
@sebastienbeau

**Comment by sebastienbeau** [comment]
I will add the test

**Comment by sebastienbeau** [comment]
@rousseldenis I have updated my added some test and also refactor the code to avoid duplicated logic between the different service.

**Review by rousseldenis — APPROVED** [review]
Code review. LGTM

**Pull request merged**
