### PR TITLE
[10.0][IMP] shopinvader_locomotive: Improve metadata

### PR DESCRIPTION
**Pull request by rousseldenis**
Sometimes, it would be necessary to have country states synchronized
with locomotive (e.g.: to manage more accurately deliveries)

### CODE REVIEW

**Comment by rousseldenis** [comment]
@Cedric-Pigeon

**Review by Cedric-Pigeon — APPROVED** [review]

**Comment by Cedric-Pigeon** [comment]
@rousseldenis just one remark. I think we should update the customer and addresses services to use this value isn't it ?

**Comment by rousseldenis** [comment]
> @rousseldenis just one remark. I think we should update the customer and addresses services to use this value isn't it ?

Nope. Already managed : https://github.com/shopinvader/odoo-shopinvader/blob/12.0/shopinvader/services/address.py#L75

**Review by Cedric-Pigeon — APPROVED** [review]

**Review by sebastienbeau — APPROVED** [review]

**Pull request merged**
