### PR TITLE
[14.0][ADD] `shopinvader_sale_automatic_workflow` : Use sale automatic workflows for Shopinvader orders 🤖

### PR DESCRIPTION
**Pull request by ivantodorovich**
Simple module that allows to set an [Automatic Workflow](https://github.com/OCA/sale-workflow/tree/14.0/sale_automatic_workflow) on created Shopinvader orders.

### CODE REVIEW

**Review by simahawk — APPROVED** [review]

**Review by jcoux — APPROVED** [review]

**Comment by lmignon** [comment]
@ivantodorovich Why don't you use [sale_automatic_workflow_payment_mode](https://github.com/OCA/sale-workflow/tree/14.0/sale_automatic_workflow_payment_mode)? No need for such a specific addon.

**Comment by ivantodorovich** [comment]
> Why don't you use [sale_automatic_workflow_payment_mode](https://github.com/OCA/sale-workflow/tree/14.0/sale_automatic_workflow_payment_mode)? No need for such a specific addon.

It's not the same though. That module wouldn't allow the same control on multi payment modes or multi shopinvader backends (with shared payment modes) environments.

For our use case, it makes sense to have a workflow that applies only to a specific backend

**Comment by simahawk** [comment]
@lmignon good for you?

**Pull request merged**
