### PR TITLE
[14.0] shopinvader_product_brand: add images support

### PR DESCRIPTION
**Pull request by sebastienbeau**
Add image support for shopinvader_product_brand.
Note I directly add the support in the shopinvader_product_brand module as it's a small module (to avoid too much glue module).
Moreover when adding brand support in e-commerce case, you will always (or 99%) need image.

- [x] depend on https://github.com/OCA/storage/pull/114
- [x] depend on https://github.com/OCA/storage/pull/130

@ivantodorovich

### CODE REVIEW

**Review by ivantodorovich — APPROVED** [review]
Unless `shopinvader_image` gets merged into `shopinvader`, I would be in favour of having this in a separate module for consistency.

**Comment by sebastienbeau** [comment]
Ok so let's split it, because I more in favour of split the shopinvader module in order to reduce the number of dependency. To be able to split the work more easier during the migration process.

**Review by simahawk — APPROVED** [review]

**Comment by simahawk** [comment]
@sebastienbeau still WIP?

**Comment by sebastienbeau** [comment]
It's ready !

**Comment by simahawk** [comment]
I'm going to test this in a while

**Comment by simahawk** [comment]
tested and working. The UI could be improved w/ a tab for images. Not a blocker tho. @sebastienbeau what do you think?

**Comment by sebastienbeau** [comment]
Yes good idea
pending PR
- https://github.com/OCA/brand/pull/87

**Pull request merged**
