### PR TITLE
[IMP] shopinvader: Add country states in countries settings route

### PR DESCRIPTION
**Pull request by paradoxxxzero**
`GET /shopinvader/settings/countries `now returns for instance:

```
[
    {
        "name": "France",
        "code": "FR",
        "id": 75,
        "state_ids": []
    },
    {
        "name": "United States",
        "code": "US",
        "id": 233,
        "state_ids": [
            {
                "name": "Armed Forces Americas",
                "code": "AA",
                "id": 68
            },
            {
                "name": "Armed Forces Europe",
                "code": "AE",
                "id": 69
            },
            # ...
            {
                "name": "Wyoming",
                "code": "WY",
                "id": 59
            }
        ]
    }
]
```

### CODE REVIEW

**Review by hparfr — APPROVED** [review]

**Comment by hparfr** [comment]
@paradoxxxzero can you please fix pre-commit ?

**Comment by paradoxxxzero** [comment]
Sure

**Review by lmignon — CHANGES_REQUESTED** [review]
@paradoxxxzero Thank you for the proposal. Why `state_ids`? Should be `states`.  Moreover, I would add a dedicated service to request states for a given country.

**Comment by paradoxxxzero** [comment]
Thanks for the review.

I renamed `state_ids` to `states`, written some tests and added an `include_states` GET parameter to only include states if you explicitly want them.

As for having a dedicated route to states, it has its pros and cons but for us this version is better (less requests for a reasonable JSON size)

**Comment by paradoxxxzero** [comment]
Is there anything still blocking? (FYI @hparfr )

**Review by sebastienbeau — APPROVED** [review]
LGTM (code review) having a state inside the country seem to be simple and ok for a first version. @lmignon ok for you ?

**Comment by lmignon** [comment]
I still prefer to have a dedicated service to request states for a given country.

**Review by mourad-ehm — APPROVED** [review]
code review

**Pull request closed without merging**
