### PR TITLE
[MIG] shopinvader_sale_packaging_wishlist: Migration to 14.0

### PR DESCRIPTION
**Pull request by chafique-delli**
Depends on :
- [x] base_jsonify https://github.com/OCA/server-tools/pull/2031
- [x] sale_product_set_packaging_qty https://github.com/OCA/sale-workflow/pull/1402
- [x] shopinvader_wishlist https://github.com/shopinvader/odoo-shopinvader/pull/867
- [x] shopinvader_sale_packaging https://github.com/shopinvader/odoo-shopinvader/pull/873
- [x] shopinvader https://github.com/shopinvader/odoo-shopinvader/pull/887

### CODE REVIEW

**Comment by simahawk** [comment]
@kevinkhao can you rebase?

**Comment by simahawk** [comment]
are these commits from v13 included already? 

[s_sale_packaging: make packaging info consistent ](https://github.com/shopinvader/odoo-shopinvader/commit/3928aee96e9e48c344249679f08cb8f37740ca78)

[s_sale_packaging_wishlist: adapt test w/ barcode data](https://github.com/shopinvader/odoo-shopinvader/commit/2b930d68e49bd64808caa457c410704a8c5d5890)

**Comment by kevinkhao** [comment]
done
1. yes, here 4088d0b1a88e6b662ca60c1568b791b26e3d6a93
2. no, added before migration commit

**Comment by kevinkhao** [comment]
https://github.com/shopinvader/odoo-shopinvader/pull/1131 was merged but module not marked as installable
I added a new commit to change it to installable + run pre-commit

**Review by simahawk — APPROVED** [review]

**Pull request merged**
