### PR TITLE
[16.0][IMP] shopinvader_product_sale_packaging: extend ProductPackaging schema

### PR DESCRIPTION
**Pull request by trisdoan**

### CODE REVIEW

**Review by simahawk — APPROVED** [review]
LGTM

**Review by lmignon — APPROVED** [review]

**Comment by lmignon** [comment]
@trisdoan Thank you for the contrib. Can you fix the tests plz.

**Comment by trisdoan** [comment]
DRAFT: working on failed tests

**Comment by trisdoan** [comment]
Hello @lmignon, tests are green, plz help to review :pray:

**Comment by lmignon** [comment]
@trisdoan Can you squash your commits so I'll merge your PR. Thank you.

**Pull request merged**
