### PR TITLE
[13.0] pre-commit upgrade align w/ OCA

### PR DESCRIPTION
**Pull request by simahawk**
For linting I removed check manifest author of course.

@sebastienbeau ping

### CODE REVIEW

**Comment by simahawk** [comment]
it would be nice to increase line lenght to 88 as done in OCA.
Maybe for a next round?

**Comment by sbidoul** [comment]
Maybe one day we should apply the OCA copier template (or a minimal variantion of it) to all shopinvader repos and branches >= 11.

**Comment by simahawk** [comment]
@sebastienbeau @lmignon good for you?

**Comment by lmignon** [comment]
Good for me... Sorry for the delay @simahawk . Missed your ping

**Pull request merged**
