### PR TITLE
[13.0][PORT] 762 from 12.0

### PR DESCRIPTION
**Pull request by sebastienbeau**
Port #762 from 12.0 to 13.0.

### CODE REVIEW

**Comment by HviorForgeFlow** [comment]
@sebastienbeau  I did some work regarding this port to v13. https://github.com/shopinvader/odoo-shopinvader/pull/683

**Comment by sebastienbeau** [comment]
@HviorForgeFlow Thanks I am going to take a look on it.
Maybe I will integrate this directly in this PR, I do not think it worth to create a separated module for this (the code in a native field on state, so It make seen to support it directly in base module)

Thanks for the link

**Comment by sebastienbeau** [comment]
After thinks twice, we should have a simple implementation in the base module (sending all state of country). Then an additional module can make it more configurable.

**Comment by sebastienbeau** [comment]
let's merge this part

**Pull request merged**
