### PR TITLE
[14.0][MIG] shopinvader_partner_vat

### PR DESCRIPTION
**Pull request by kevinkhao**
taken from https://github.com/shopinvader/odoo-shopinvader/pull/960
rebased on 14.0

### CODE REVIEW

**Review by lmignon — APPROVED** [review]

**Comment by lmignon** [comment]
@kevinkhao Can you resolve the conflict so we can  proceed to the merge? Thank you.

**Comment by kevinkhao** [comment]
should be ok

**Comment by lmignon** [comment]
Thank you @kevinkhao

**Comment by lmignon** [comment]
@kevinkhao Thank for for the fix. unfortunately, it seems that somthing is wrong with pre-commit...
image

**Comment by kevinkhao** [comment]
my bad, should be ok now

**Pull request merged**
