### PR TITLE
 [14.0] shopinvader_auth_api_key: fix auth api key docs

### PR DESCRIPTION
**Pull request by simahawk**
Not sure why the original PR is closed here https://github.com/shopinvader/odoo-shopinvader/pull/1107

### CODE REVIEW

**Comment by simahawk** [comment]
```
  File "/home/runner/.cache/pre-commit/reponejii91s/py_env-python3/lib/python3.10/site-packages/astroid/modutils.py", line 210, in load_module_from_name
    return importlib.import_module(dotted_name)
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/.cache/pre-commit/reponejii91s/py_env-python3/lib/python3.10/site-packages/pylint/checkers/imports.py", line 49, in <module>
    import isort
  File "/home/runner/.cache/pre-commit/reponejii91s/py_env-python3/lib/python3.10/site-packages/isort/__init__.py", line 25, in <module>
    from . import settings  # noqa: F401
  File "/home/runner/.cache/pre-commit/reponejii91s/py_env-python3/lib/python3.10/site-packages/isort/settings.py", line 34, in <module>
    from .pie_slice import itemsview, lru_cache, native_str
  File "/home/runner/.cache/pre-commit/reponejii91s/py_env-python3/lib/python3.10/site-packages/isort/pie_slice.py", line 362, in <module>
    class OrderedSet(collections.MutableSet):
AttributeError: module 'collections' has no attribute 'MutableSet'
```
@sbidoul is there anything to change in pre-commit dependencies?

**Comment by sbidoul** [comment]
ah, yes, we need to apply https://github.com/OCA/oca-addons-repo-template/pull/79 here too.

**Comment by simahawk** [comment]
Ahh, ok. I have this same error on OCA/wms too. I guess because this is not merged yet https://github.com/OCA/wms/pull/313 right?
As per shopinvader repo, I guess we have to integrate it here https://github.com/shopinvader/shopinvader-addons-repo-template ?

**Comment by sbidoul** [comment]
> Ahh, ok. I have this same error on OCA/wms too. I guess because this is not merged yet [OCA/wms#313](https://github.com/OCA/wms/pull/313) right? 

yes

> As per shopinvader repo, I guess we have to integrate it here https://github.com/shopinvader/shopinvader-addons-repo-template ?

yes, and then apply it to all repos (I think I used https://github.com/OCA/maintainer-tools/pull/486 for shopinvader too)

**Review by ivantodorovich — APPROVED** [review]

**Pull request merged**
