### PR TITLE
[13.0][IMP] base_url: Allow to add slashes on manual_url_key

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Allow to build manual_url_key with slashes

CC @ForgeFlow

### CODE REVIEW

**Review by acsonefho — CHANGES_REQUESTED** [review]
A unit test should be welcome to cover this case.

**Review by PierrickBrun — APPROVED** [review]

**Review by hparfr — CHANGES_REQUESTED** [review]
There should be no slash in the sluggified part of the url by design.

Can you please share your use case ?

**Comment by HviorForgeFlow** [comment]
Using this feature + modifying _post_process_url_key method to put the category before the product.
Example product: Table category: Forniture
www.shop.com/forniture/table 
I couldn't find another way to solve this request.

**Comment by hparfr** [comment]
> Using this feature + modifying _post_process_url_key method to put the category before the product. Example product: Table category: Forniture [www.shop.com/forniture/table](http://www.shop.com/forniture/table) I couldn't find another way to solve this request.

You may use [_post_process_url_key](https://github.com/shopinvader/odoo-shopinvader/blob/14.0/base_url/models/abstract_url.py#L76)
```
    def _post_process_url_key(self, key):
        """This method allow you to customized the url key.
        you can use it to build full path be adding the url of parent record
        Ex: key is 42 you can prefix it with "foo" and so return "foo/42"
        Note: the self do not include in the context the lang of the record
        """```

**Pull request closed without merging**
