### PR TITLE
[MIG] 14.0 elasticsearch

### PR DESCRIPTION
**Pull request by PierrickBrun**
Depends of
- [x] connector https://github.com/OCA/connector/pull/385
- [x] connector_search_engine https://github.com/OCA/search-engine/pull/67
- [x] connector_elasticsearch https://github.com/OCA/search-engine/pull/67

### CODE REVIEW

**Review by bguillot — APPROVED** [review]

**Comment by simahawk** [comment]
@PierrickBrun can you drop pending merges and rebase after https://github.com/shopinvader/odoo-shopinvader/pull/966 gets merged?

**Comment by sebastienbeau** [comment]
@simahawk I have going to rebase this one after merging https://github.com/shopinvader/odoo-shopinvader/pull/966

**Comment by sebastienbeau** [comment]
ah ah same time ;)

**Comment by simahawk** [comment]
you can rebase now ;)

**Comment by sebastienbeau** [comment]
let's go

**Comment by sebastienbeau** [comment]
@simahawk ready to be approved and merged

**Review by simahawk — APPROVED** [review]

**Pull request merged**
