### PR TITLE
[14.0][ADD] shopinvader_product_stock_forecast_expiry

### PR DESCRIPTION
**Pull request by ivantodorovich**
This module has the forecast take into account the lot expiration dates from `product_expiry` module

### CODE REVIEW

**Comment by ivantodorovich** [comment]
CI is failing but I believe it's related to :
- https://github.com/shopinvader/odoo-shopinvader/pull/1164

```python-traceback
Traceback (most recent call last):
  File "/__w/odoo-shopinvader/odoo-shopinvader/setup/shopinvader/odoo/addons/shopinvader/tests/test_cart.py", line 119, in test_anonymous_cart_then_sign
    self._sign_with(invader_partner)
  File "/__w/odoo-shopinvader/odoo-shopinvader/setup/shopinvader/odoo/addons/shopinvader/tests/test_cart.py", line 113, in _sign_with
    service_sign.sign_in()
  File "/opt/odoo-venv/lib/python3.6/site-packages/odoo/addons/base_rest/restapi.py", line 102, in response_wrap
    response = f(*args, **kw)
  File "/__w/odoo-shopinvader/odoo-shopinvader/setup/shopinvader/odoo/addons/shopinvader/services/customer.py", line 59, in sign_in
    return self._assign_cart_and_get_store_cache()
  File "/__w/odoo-shopinvader/odoo-shopinvader/setup/shopinvader/odoo/addons/shopinvader/services/customer.py", line 145, in _assign_cart_and_get_store_cache
    cart = self._get_and_assign_cart()
  File "/__w/odoo-shopinvader/odoo-shopinvader/setup/shopinvader/odoo/addons/shopinvader/services/customer.py", line 140, in _get_and_assign_cart
    return cart_service._to_json(cart)["data"]
  File "/__w/odoo-shopinvader/odoo-shopinvader/setup/shopinvader/odoo/addons/shopinvader/services/cart.py", line 418, in _to_json
    res = super(CartService, self)._to_json(cart)[0]
  File "/__w/odoo-shopinvader/odoo-shopinvader/setup/shopinvader/odoo/addons/shopinvader/services/abstract_sale.py", line 120, in _to_json
    res.append(self._convert_one_sale(sale))
  File "/__w/odoo-shopinvader/odoo-shopinvader/setup/shopinvader/odoo/addons/shopinvader/services/abstract_sale.py", line 29, in _convert_one_sale
    "lines": self._convert_lines(sale),
  File "/__w/odoo-shopinvader/odoo-shopinvader/setup/shopinvader/odoo/addons/shopinvader/services/abstract_sale.py", line 82, in _convert_lines
    items.append(self._convert_one_line(line))
  File "/__w/odoo-shopinvader/odoo-shopinvader/setup/shopinvader/odoo/addons/shopinvader/services/abstract_sale.py", line 60, in _convert_one_line
    product = self._convert_one_line_product(variant)
  File "/__w/odoo-shopinvader/odoo-shopinvader/setup/shopinvader/odoo/addons/shopinvader/services/abstract_sale.py", line 76, in _convert_one_line_product
    return variant.get_shop_data() if variant else {}
  File "/__w/odoo-shopinvader/odoo-shopinvader/setup/shopinvader/odoo/addons/shopinvader/models/shopinvader_variant.py", line 322, in get_shop_data
    return self._get_shop_data()
  File "/__w/odoo-shopinvader/odoo-shopinvader/setup/shopinvader/odoo/addons/shopinvader/models/shopinvader_variant.py", line 327, in _get_shop_data
    return self.jsonify(exporter.get_json_parser(), one=True)
  File "/opt/odoo-venv/lib/python3.6/site-packages/odoo/addons/base_jsonify/models/models.py", line 136, in jsonify
    self._jsonify_record(parsers[lang], record, json)
  File "/opt/odoo-venv/lib/python3.6/site-packages/odoo/addons/base_jsonify/models/models.py", line 77, in _jsonify_record
    field = rec._fields[field_name]
KeyError: 'manufactured_for_partners'
```

ping @kv1612

**Comment by simahawk** [comment]
you need this https://github.com/OCA/server-tools/pull/2220 ;)

**Review by simahawk — APPROVED** [review]

**Review by damdam-s — APPROVED** [review]

**Review by hparfr — APPROVED** [review]
/ocabot merge nobump

**Comment by ivantodorovich** [comment]
@hparfr the merge error seems unrelated to the pr:

```
  /usr/bin/docker --config /home/runner/work/_temp/.docker_428794c6-96e6-4b33-8adb-f2e94c972e0a login ghcr.io -u shopinvader-git-bot --password-stdin
  Error: Docker login for 'ghcr.io' failed with exit code 1
```

Could you please try again? 🙏🏻

**Pull request merged**
