### PR TITLE
[MIG] 14.0 locomotive

### PR DESCRIPTION
**Pull request by PierrickBrun**
based on #855

### CODE REVIEW

**Comment by rousseldenis** [comment]
@PierrickBrun Could you remove dependencies in test-requirements.txt ?

**Comment by PierrickBrun** [comment]
> @PierrickBrun Could you remove dependencies in test-requirements.txt ?

These dependencies are not merged yet

**Comment by simahawk** [comment]
@PierrickBrun base PRs are merged, can you rebase?
Also, while doing it, please cherry pick these commits from v13: https://github.com/shopinvader/odoo-shopinvader/commit/3d1e123c1636438dd5c40718c88e2bc0041a665e and https://github.com/shopinvader/odoo-shopinvader/commit/3588e305583658379ca0957fcf7c2119ec52f37f

**Comment by simahawk** [comment]
Replaced by #974

Sorry guys, is getting insane w/ pending merges :sweat_smile:  and I kind of need to move faster :wink: 

I've included the 2 mentioned commits from v14 :wink:

**Comment by rousseldenis** [comment]
> Replaced by #974
> 
> Sorry guys, is getting insane w/ pending merges  and I kind of need to move faster 
> 
> I've included the 2 mentioned commits from v14

Yes, I'll have a look. I'll have more time soon for shopinvader v14.

**Pull request closed without merging**
