### PR TITLE
[14.0][FIX] fix build

### PR DESCRIPTION
**Pull request by mmequignon**
ATM, every PR fails, trying to fix this here.

Any help and insights are welcome :pray: 

Thanks!

### CODE REVIEW

**Comment by simahawk** [comment]
@sbidoul @sebastienbeau  can we finally fix this? https://github.com/shopinvader/locomotivecms-python-client/issues/5

It's causing 
image

**Comment by simahawk** [comment]
> @sbidoul @sebastienbeau can we finally fix this? [shopinvader/locomotivecms-python-client#5](https://github.com/shopinvader/locomotivecms-python-client/issues/5)


FYI I've disabled the check for `locomotivecms` for now. See [`f108e17` (#1532)](https://github.com/shopinvader/odoo-shopinvader/pull/1532/commits/f108e176439c01f3752694506e9de52286afbdc6)

**Comment by simahawk** [comment]
Bumping modules' versions manually as the bot does not work. I'll merge w/ the btn directly.

@sbidoul are you aware of any issue w/ the bot on 14.0?

**Comment by sbidoul** [comment]
> Bumping modules' versions manually as the bot does not work. I'll merge w/ the btn directly.
> 
> @sbidoul are you aware of any issue w/ the bot on 14.0?

@simahawk Yeah, it has stability issue that I could not pinpoint so far. I restarted it.

**Pull request merged**
