### PR TITLE
[14.0][MIG] shopinvader_delivery_carrier_category_keep_carrier from 10.0

### PR DESCRIPTION
**Pull request by acsonefho**
Migration of `shopinvader_delivery_carrier_category_keep_carrier` from https://github.com/shopinvader/odoo-shopinvader/pull/715

Depends on https://github.com/OCA/delivery-carrier/pull/403

### CODE REVIEW

**Comment by lmignon** [comment]
@acsonefho Can you rebase  to relaunch the build since https://github.com/OCA/delivery-carrier/pull/403 is merged.

**Comment by acsonefho** [comment]
@shopinvader/shopinvader-maintainers

**Comment by acsonefho** [comment]
@shopinvader/shopinvader-maintainers Can you review and merge please?

**Review by PierrickBrun — APPROVED** [review]
Code review

**Review by florian-dacosta — APPROVED** [review]
LGTM code review

**Comment by acsonefho** [comment]
@hparfr It's not possible to merge due to a strange thing in queue job. Please check https://github.com/OCA/queue/pull/440

**Pull request merged**
