### PR TITLE
[13.0][IMP] shopinvader: enclose shopinvader partner form view within sheet

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**

### CODE REVIEW

**Review by HviorForgeFlow — APPROVED** [review]

**Review by ivantodorovich — APPROVED** [review]
Similar to https://github.com/shopinvader/odoo-shopinvader/pull/1152 (`14.0`)

**Comment by simahawk** [comment]
@JordiMForgeFlow to ease fwd/backport could you cherry-pick changes from #1152 ?
Having different commits for the same thing is a bit hard to handle cross versions.

**Comment by JordiMForgeFlow** [comment]
@simahawk done! :)

**Comment by JordiMForgeFlow** [comment]
Hi @simahawk 

Could we get this merged? :)

**Comment by JordiMForgeFlow** [comment]
Hi @sebastienbeau 

Could we get this merged? :)

**Comment by HviorForgeFlow** [comment]
ping @simahawk

**Comment by simahawk** [comment]
> @JordiMForgeFlow to ease fwd/backport could you cherry-pick changes from #1152 ? Having different commits for the same thing is a bit hard to handle cross versions.

I don't see these commits, am I missing smth?

**Comment by JordiMForgeFlow** [comment]
Hi @simahawk 

Sorry about that, could you check now? :)

**Comment by simahawk** [comment]
pre-commit needs some love ;)

**Comment by HviorForgeFlow** [comment]
@simahawk any insight of what modify on pre-commit configuration to make it work? I tried using python 3.8, new pre-commit version but error persist.

Thanks!

CC @sbidoul

**Comment by simahawk** [comment]
> ImportError: cannot import name '_unicodefun' from 'click' (/home/runner/.cache/pre-commit/repojip2qi9v/py_env-python3/lib/python3.9/site-packages/click/__init__.py)

AFAIR we still have to update the template and apply it to all branches. I see there's an attempt for v12 here https://github.com/shopinvader/odoo-shopinvader/pull/1275.

We should probably sync https://github.com/shopinvader/shopinvader-addons-repo-template w/ the OCA template.
Would you mind to have a look at this?

**Comment by HviorForgeFlow** [comment]
@simahawk pre-commit fixed!

**Comment by JordiMForgeFlow** [comment]
🎉 Thank you @HviorForgeFlow :))

**Pull request merged**
