### PR TITLE
[FIX] action server in tree view must play on all selected records

### PR DESCRIPTION
**Pull request by bguillot**
Hi,

The action server in tree view works only on the first selected record.

The PR fixes it. It is a port of PR https://github.com/shopinvader/odoo-shopinvader/pull/458

### CODE REVIEW

**Review by simahawk — CHANGES_REQUESTED** [review]
variable name to be fixed on v10 PR 1st https://github.com/shopinvader/odoo-shopinvader/pull/458

**Comment by rousseldenis** [comment]
@simahawk #458 is merged

**Comment by rousseldenis** [comment]
@bguillot I see three commits in #458, is this complete ?

**Comment by rousseldenis** [comment]
@bguillot Any news on this ?

**Comment by sebastienbeau** [comment]
replaced by https://github.com/shopinvader/odoo-shopinvader/pull/761

**Pull request closed without merging**
