### PR TITLE
[13.0] [MIG] shopinvader_backend_image_proxy

### PR DESCRIPTION
**Pull request by ThomasBinsfeld**

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Trivial migration

**Review by Laurent-Corron — APPROVED** [review]
:+1:

**Comment by ThomasBinsfeld** [comment]
@sebastienbeau I'm not sure why the merge failed. I rebased on 13.0. Could you try again please?

**Comment by hparfr** [comment]
@ThomasBinsfeld can you please rebase on v13 ?

**Comment by ThomasBinsfeld** [comment]
> @ThomasBinsfeld can you please rebase on v13 ?

Done

**Pull request merged**
