### PR TITLE
shopinvader: cart fix override invoice address by policy

### PR DESCRIPTION
**Pull request by simahawk**
The policy field was used for update only but not for create.

### CODE REVIEW

**Review by sebastienbeau — APPROVED** [review]
LGTM code review

**Comment by simahawk** [comment]
@sebastienbeau have you already faced/fixed this issue? https://travis-ci.com/github/shopinvader/odoo-shopinvader/jobs/455907247#L293
Otherwise I check.

**Comment by simahawk** [comment]
ah seems the pre-commit of pylint should be upgraded

**Comment by simahawk** [comment]
hopefully fixed by https://github.com/shopinvader/odoo-shopinvader/pull/825

**Pull request merged**
