### PR TITLE
[12.0][RM] product_stock_state  New home will be in product-attribute

### PR DESCRIPTION
**Pull request by hparfr**
Wait https://github.com/OCA/product-attribute/pull/575 to be merged.
related #573

### CODE REVIEW

**Comment by kevinkhao** [comment]
Thanks @hparfr, I will post this kind of PR from now on too

**Comment by hparfr** [comment]
@kevinkhao please review now

**Comment by bealdav** [comment]
push -f :1st_place_medal:

**Comment by sebastienbeau** [comment]
\o/ product_stock_state is now merged so let's clear it from here.

/ocabot merge

**Review by sebastienbeau — APPROVED** [review]

**Pull request merged**
