### PR TITLE
 [FIX] 10.0 backport - shopinvader_locomotive: Provides the right url entrypoint for REST services

### PR DESCRIPTION
**Pull request by PierrickBrun**
depends on #536

### CODE REVIEW

**Comment by rousseldenis** [comment]
@PierrickBrun Don't forget to update https://github.com/shopinvader/odoo-shopinvader/issues/416

**Comment by simahawk** [comment]
@PierrickBrun FTR the last version from 12.0 and 13.0 is a bit more simplified
https://github.com/shopinvader/odoo-shopinvader/blob/12.0/shopinvader_locomotive/component/shopinvader_site_export_mapper.py

It also has dynamic lookup for search engine settings.
You might want to backport those changes later, after you merged this ;)

**Comment by sebastienbeau** [comment]
@PierrickBrun can you check travis and look to @simahawk comment ? maybe we can backport the simplification too?

**Comment by lmignon** [comment]
Closing since 10.0 is no more actively maintained.

**Pull request closed without merging**
