### PR TITLE
[16.0] shopinvader_api_cart: add /new endpoint

### PR DESCRIPTION
**Pull request by simahawk**
Allows to force creation of carts the same customer.

### CODE REVIEW

**Review by mmequignon — APPROVED** [review]

**Review by lmignon — APPROVED** [review]

**Comment by lmignon** [comment]
@qgroulard What about the merge mechanism with anonymous users?

**Comment by qgroulard** [comment]
> @qgroulard What about the merge mechanism with anonymous users?

It will merge one of the anonymous carts with one of the carts of the user.

@simahawk More globally, why do you need several carts and how do you expect them to work ?
Some part of shopinvader are not meant to work with multiple carts (at least I know [this method](https://github.com/shopinvader/odoo-shopinvader/blob/d39053ccc2222673e229af14b794bee2a851154f/shopinvader_sale_cart/models/sale_order.py#L26C1-L26C59) (and the anonymous cart)).

**Review by cyrilmanuel — APPROVED** [review]

**Comment by simahawk** [comment]
> > @qgroulard What about the merge mechanism with anonymous users?
> 
> It will merge one of the anonymous carts with one of the carts of the user.

Yes. Of course, this is not meant to be used by anon users.

> @simahawk More globally, why do you need several carts and how do you expect them to work ? Some part of shopinvader are not meant to work with multiple carts (at least I know [this method](https://github.com/shopinvader/odoo-shopinvader/blob/d39053ccc2222673e229af14b794bee2a851154f/shopinvader_sale_cart/models/sale_order.py#L26C1-L26C59) (and the anonymous cart)).

When you create one you get the UUID so you don´t need to find it later to update it.

/ocabot merge minor

**Pull request merged**
