### PR TITLE
[14.0][IMP] shopinvader: Add payment term in abstract sale json + add…

### PR DESCRIPTION
**Pull request by rousseldenis**
… FR tests

### CODE REVIEW

**Review by ivantodorovich — APPROVED** [review]

**Review by hparfr — APPROVED** [review]
/ocabot merge minor

**Review by acsonefho — APPROVED** [review]

**Comment by rousseldenis** [comment]
@hparfr I've added the payment term in customer service too

**Comment by hparfr** [comment]
> Error: The log was not found. It may have been deleted based on retention settings. 

Can't check the pre-commit issue. (and did not find the button to restart it)

**Comment by sebastienbeau** [comment]
@rousseldenis can you rebase, so we can merge it

**Pull request closed without merging**
