### PR TITLE
[12.0][PORT] #607 and #340 port from 10.0: [FIX] fix issue when creating binding from the main record

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Port #607 and #340 from 10.0 to 12.0

### CODE REVIEW

**Comment by rousseldenis** [comment]
@HviorForgeFlow Needs https://github.com/shopinvader/odoo-shopinvader/pull/340

**Review by rousseldenis — APPROVED** [review]

**Comment by rousseldenis** [comment]
@HviorForgeFlow Could you rebase this ?

**Comment by HviorForgeFlow** [comment]
@rousseldenis done!

**Pull request merged**
