### PR TITLE
[14.0][IMP] shopinvader_sale_profile: Do not use fiscal position on sale profile computation when fpos are not configured

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Port https://github.com/shopinvader/odoo-shopinvader/pull/1204

CC @simahawk @ForgeFlow

### CODE REVIEW

**Comment by simahawk** [comment]
build is :red_circle:

**Review by lmignon — CHANGES_REQUESTED** [review]
@HviorForgeFlow Thank you for this contribution. Can yo add a test to cover this specific use case?

**Review by lmignon — APPROVED** [review]
Thank you @HviorForgeFlow. LGTM (code review)

**Comment by HviorForgeFlow** [comment]
@lmignon have you seen this PR? https://github.com/shopinvader/odoo-shopinvader/pull/1153

It will collide merging this one.

**Comment by lmignon** [comment]
@HviorForgeFlow Do you mean this one should be closed and we should merge #1153?

**Comment by HviorForgeFlow** [comment]
I didn't test #1153, this one solved my use case in v13, let's merge the other one, and then when needed I can reopen an slightly different version of this one.

**Comment by lmignon** [comment]
superseded by #1153

**Pull request closed without merging**
