### PR TITLE
[14.0][IMP] shopinvader: Restore binding wizard on partner view

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@lmignon I think this could be backported due to https://github.com/shopinvader/odoo-shopinvader/commit/b8fec48e92902880dd53830d0c07c9f154c1b764#diff-4ccbe241c12d3a9cdeb00445fc9b2c59ee604afdfb8b816e0978224765418708R38

**Comment by Mat-moran** [comment]
Hi,

I am testing it, I can see the wizard but I can not do any action inside it because does not show any partner in the list.

image

image

I do not know if this should be the behavior or I need to do something else.

**Comment by kevinkhao** [comment]
functional test


Screenshot from 2021-10-04 14-12-15


works as expected with binding generated

@Mat-moran maybe the partner was already bound ?

**Review by kevinkhao — APPROVED** [review]

**Comment by Mat-moran** [comment]
@kevinkhao you were right!  The wizar works fine. The partner was binded. Thanks

**Comment by kevinkhao** [comment]
@Mat-moran could you help approve if it works ?

**Review by Mat-moran — APPROVED** [review]
Works fine!

**Comment by Mat-moran** [comment]
Thanks for ping @kevinkhao is my first approvement, I did't know how to do it.  regards

**Pull request merged**
