### PR TITLE
[MIG] shopinvader_product_template_multi_link: Migration to 14.0

### PR DESCRIPTION
**Pull request by chafique-delli**

### CODE REVIEW

**Review by acsonefho — APPROVED** [review]
Code LGTM

**Comment by sebastienbeau** [comment]
@chafique-delli can you rebase ?

**Comment by chafique-delli** [comment]
> @chafique-delli can you rebase ?

@sebastienbeau , it's done.

**Comment by simahawk** [comment]
please make sure you include this fix https://github.com/shopinvader/odoo-shopinvader/pull/1003
also, https://github.com/OCA/e-commerce/pull/489 is merged, please drop the dependency

**Comment by simahawk** [comment]
FTR there are some fix/imp to be fwd ported on base modules that I've reported here https://github.com/OCA/e-commerce/pull/495 and would be nice if you rebase and test w/ those changes included.

**Comment by acsonefho** [comment]
@chafique-delli did you plan to fix this PR? Or I can do it?

**Comment by simahawk** [comment]
ping :)

**Comment by simahawk** [comment]
replaced by https://github.com/shopinvader/odoo-shopinvader/pull/1073

**Pull request closed without merging**
