### PR TITLE
[14.0] shopinvader: forward port all recent goodies from v13

### PR DESCRIPTION
**Pull request by simahawk**
See atomic commits for details.

Main improvements:

1. shopinvader: centralize partner work ctx setup
2. shopinvader: partner form quick edit form for invader partner
3. shopinvader: refactor partner validation
4. shopinvader: product filter custom path for fields
5. shopinvader: refactor and improve binding wiz
6. shopinvader: support like/ilike for searches
7. shopinvader: propagate params to json rendering

NOTE: PR split in N parts:

- [x] #984 
- [x] #986 
- [ ] #989
- [ ] #991

### CODE REVIEW

**Comment by simahawk** [comment]
@sbidoul any clue on what's going on here?

https://github.com/shopinvader/odoo-shopinvader/runs/2654953302?check_suite_focus=true
```
Run oca_init_test_database
+ oca_wait_for_postgres
postgres:5432 - accepting connections
++ addons --addons-dir . --include '' --exclude '' list-depends
/usr/local/bin/addons: line 2: /opt/acsoo/bin/acsoo: No such file or directory
+ ADDONS=
Error: Process completed with exit code 127.
```

looks like it does not find modules to install and provides an empty list

**Comment by sbidoul** [comment]
Hm, it looks like I goofed while fiddling with the oca-ci. Can you please retry when https://github.com/OCA/oca-ci/commit/5d9abb1bc0a44dd1163e77918e124f1bd1e9a182 is green ?

I'm working to replace acsoo and oca_list_external_dependencies in oca-ci with [manifestoo](https://pypi.org/project/manifestoo/), which also allows interesting (and much overdue) things like #971.

**Comment by simahawk** [comment]
@sbidoul much better thanks! :+1:

**Comment by simahawk** [comment]
@shopinvader/shopinvader-maintainers this one is important as it aligns all main fixes/imp w/ v13. Any review is much appreciated :pray: I could split it in more PR w/ smaller chunks if you prefer.

**Comment by hparfr** [comment]
Hi thanks for this work.

Can you please not change the __manifest__ in order to avoid conflicts.

I did a quick test, I got some issues with the unbinding wizard of the categories

```
File "/odoo/src/odoo/models.py", line 6148, in onchange
    if cmd[0] in (1, 4):
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo/src/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/src/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: 'int' object is not subscriptable

```

Didn't had time to investigate more

**Comment by simahawk** [comment]
@hparfr I don't get why I should drop the manifest change: I have a migration to run.
Also, could you be more explicit on your error?

**Comment by simahawk** [comment]
rebased

**Comment by simahawk** [comment]
@hparfr to ease your life and reduce diff here I split the 1st part to https://github.com/shopinvader/odoo-shopinvader/pull/984
Those changes are pretty straight forward, can we fast track them? Then I'll split the rest here.

**Comment by simahawk** [comment]
2nd round https://github.com/shopinvader/odoo-shopinvader/pull/986

**Comment by hparfr** [comment]
>@hparfr I don't get why I should drop the manifest change: I have a migration to run.

True, but there is conflicts with 14.0, so review is harder to do. Do not know what is the good practice.

**Comment by simahawk** [comment]
well, if you don't get the conflict you can miss the right version bump and thus miss the upgrade step which is fundamental if you don't won't a broken instance. I'll move that part to a separated PR later. For now I split the PR so you can easily review each bit. See #986 for the binding wizard.

**Comment by simahawk** [comment]
round 3 https://github.com/shopinvader/odoo-shopinvader/pull/989

**Comment by simahawk** [comment]
closing this to not generate confusion.
The last parts that I split are on:

#989
#991

**Pull request closed without merging**
