### PR TITLE
ADD module 10.0 shopinvader_partner_address_street3

### PR DESCRIPTION
**Pull request by bealdav**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@bealdav Could you check Travis ? It's pre-commit error.

**Comment by bealdav** [comment]
Please @rousseldenis I've another error
https://github.com/akretion/odoo-shopinvader/runs/2201140755?check_suite_focus=true#step:4:121

It's seems there is a discord between flake8 and black
`shopinvader_partner_address_street3/services/customer.py:15:62: E231 missing whitespace after ','`

How can I deal with that ?

Could we escape E231 ? How to do that ? Where should I specify it ?

Thanks

**Comment by bealdav** [comment]
Please @sebastienbeau coul you have a look here ?

**Comment by bealdav** [comment]
Rebased

**Comment by sebastienbeau** [comment]
@bealdav can you fix the test please ?

**Comment by lmignon** [comment]
Closing since 10.0 is no more actively maintained.

**Pull request closed without merging**
