### PR TITLE
[REF] shopinvader_product: Remove price

### PR DESCRIPTION
**Pull request by simahawk**
There are a lot of different ways to expose product prices, those should be handled in dedicated modules.

'_get_price()' method has been extracted to OCA/product-attribute module 'product_get_price_helper'.

Taken out of https://github.com/shopinvader/odoo-shopinvader/pull/1498

### CODE REVIEW

**Review by qgroulard — APPROVED** [review]

**Comment by simahawk** [comment]
is there a problem w/ the bot?

**Comment by simahawk** [comment]
@sbidoul any clue?

**Review by mmequignon — APPROVED** [review]

**Comment by simahawk** [comment]
Let's give it another try

/ocabot merge patch

**Pull request merged**
