### PR TITLE
shopinvader_algolia: migrate to v12

### PR DESCRIPTION
**Pull request by simahawk**
testing locally ATM, seems good tho.
The hook I don't know if it's still useful or not...
I have not updated `super(...)` calls to ease forward / backports.

### CODE REVIEW

**Review by lmignon — APPROVED** [review]
Not blocking but IMO we should remove the post_init_hook

**Comment by lmignon** [comment]
pre-commit is failing :red_circle:

**Comment by simahawk** [comment]
fixed, sorry ;P

**Pull request merged**
