### PR TITLE
[BKP] 10.0 backport partner_firstname

### PR DESCRIPTION
**Pull request by PierrickBrun**

### CODE REVIEW

**Review by simahawk — APPROVED** [review]
LG

**Comment by simahawk** [comment]
build is red

**Review by Cedric-Pigeon — APPROVED** [review]
code review

**Comment by Cedric-Pigeon** [comment]
@PierrickBrun Can you please check travis to go ahead? Thanks

**Comment by sebastienbeau** [comment]
@PierrickBrun can you check Travis? and ping me when it's green

**Comment by rousseldenis** [comment]
@PierrickBrun Could you rebase ?

**Comment by PierrickBrun** [comment]
Work continued in https://github.com/shopinvader/odoo-shopinvader/pull/845

**Pull request closed without merging**
