### PR TITLE
[10.0][IMP] shopinvader_product_stock: Allow to exclude locations

### PR DESCRIPTION
**Pull request by rousseldenis**
Depends on:

* [x] https://github.com/OCA/stock-logistics-warehouse/pull/893

Change:

* [x] oca_dependencies.txt

### CODE REVIEW

**Comment by rousseldenis** [comment]
@Cedric-Pigeon

**Comment by sebastienbeau** [comment]
@rousseldenis Thanks for the good work (with test) and the interesting feature.

Not sure that we should have this by default or if we should have an extra module "shopinvader_product_stock_exclude_location" ? Having let dependency is always good for migrating the projetc with the first customer (less work)
@Cedric-Pigeon @lmignon what do you think?

**Comment by Cedric-Pigeon** [comment]
@rousseldenis could you please rebase this one ?

**Comment by rousseldenis** [comment]
@Cedric-Pigeon @lmignon What do you think? Maybe we can do another module for that purpose

**Comment by Cedric-Pigeon** [comment]
Yes I agree. Especially because this feature is definitely not a must-have. It would be better to isolate it within a dedicated addon

**Comment by lmignon** [comment]
@rousseldenis I agreee with @sebastienbeau... This functionality should go into its own addon

**Comment by hparfr** [comment]
@rousseldenis can we close this one ?

**Pull request closed without merging**
