### PR TITLE
[13.0] Backport UI improvements

### PR DESCRIPTION
**Pull request by simahawk**
https://github.com/shopinvader/odoo-shopinvader/pull/1059

### CODE REVIEW

**Comment by simahawk** [comment]
@sbidoul could you check this build? https://github.com/shopinvader/odoo-shopinvader/runs/3370143981#step:4:57
Seems weird.

**Comment by sbidoul** [comment]
@simahawk I restarted the simpleindex service on odoo-community.org. Please retry.

**Pull request merged**
