### PR TITLE
[13.0] Add shopinvader_customer_multi_user

### PR DESCRIPTION
**Pull request by simahawk**
FWD port of #471 

~~Includes https://github.com/shopinvader/odoo-shopinvader/pull/543~~

### CODE REVIEW

**Comment by simahawk** [comment]
@lmignon @sebastienbeau a review would be much appreciated :pray:

**Review by lmignon — APPROVED** [review]

**Review by Cedric-Pigeon — APPROVED** [review]
Code review only

**Comment by simahawk** [comment]
ops, UI was not refreshed :sweat_smile: I blocked the new build.
Thanks for approving and merging :)

**Pull request merged**
