### PR TITLE
[14.0][FIX] simultaneous product.template+binding creation creates the binding in inactive state

### PR DESCRIPTION
**Pull request by kevinkhao**

### CODE REVIEW

**Review by sebastienbeau — APPROVED** [review]
LGTM (code review)

**Comment by sebastienbeau** [comment]
@PierrickBrun can you review

**Comment by kevinkhao** [comment]
+sneaky minor addition: boolean toggle
Screenshot from 2021-10-06 20-19-59

**Review by PierrickBrun — APPROVED** [review]
Nice addition, thanks (code review)

**Review by lmignon — APPROVED** [review]
LGTM (code review)

**Pull request merged**
