### PR TITLE
[MIG][14.0] shopinvader_customer_autobind: Migration from 10.0

### PR DESCRIPTION
**Pull request by acsonefho**
Based on PR: https://github.com/shopinvader/odoo-shopinvader/pull/713

Changes, compared to original PR:
Mark automatically the new partner created as a customer (`customer_rank > 0`)

### CODE REVIEW

**Comment by sebastienbeau** [comment]
@thibaultrey I think this will interest you

**Review by kevinkhao — APPROVED** [review]
Functional tested. Works as expected, bindings are created for every backend
nitpicking, non-blocking: demo mail template could use partner's email address

**Comment by sebastienbeau** [comment]
@acsonefho  can you rebase ?

**Comment by sebastienbeau** [comment]
can you rebase to make it green so we can merge it

**Comment by sebastienbeau** [comment]
@acsonefho test are failing can you check ?

**Comment by acsonefho** [comment]
> @acsonefho test are failing can you check ?

All are green now :muscle: :green_circle:

**Pull request merged**
