### PR TITLE
[14.0][MIG] migrate shopinvader_product_stock_assortment

### PR DESCRIPTION
**Pull request by Cedric-Pigeon**

### CODE REVIEW

**Review by sebastienbeau — APPROVED** [review]
LGTM code review

**Comment by sebastienbeau** [comment]
@Cedric-Pigeon can you rebase ?

**Comment by Cedric-Pigeon** [comment]
@sebastienbeau done ;-)

**Comment by sebastienbeau** [comment]
@Cedric-Pigeon There is an issue with pre commit ;)

**Comment by sebastienbeau** [comment]
@Cedric-Pigeon There is an issue with pre commit ;)

**Comment by Cedric-Pigeon** [comment]
@sebastienbeau fixed.

**Pull request merged**
