### PR TITLE
[14.0][ADD] adds shopinvader_sale_price_update

### PR DESCRIPTION
**Pull request by Cedric-Pigeon**
This new addons allows to recompute all carts linked to a backend in case of pricelist change.

See #679

### CODE REVIEW

**Review by kevinkhao — COMMENTED** [review]
manual test: demo data (so, we have demo carts linked to a backend), 

on clicking Launch Price Update:


```
Odoo Server Error
Traceback (most recent call last):
  File "/home/khkhkh/odoo/14.0/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/khkhkh/odoo/14.0/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/home/khkhkh/odoo/14.0/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/khkhkh/odoo/14.0/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/khkhkh/odoo/14.0/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/khkhkh/odoo/14.0/odoo/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/home/khkhkh/odoo/14.0/odoo/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/home/khkhkh/odoo/14.0/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/khkhkh/odoo/14.0/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/khkhkh/odoo/14.0/odoo/odoo/api.py", line 392, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/home/khkhkh/odoo/14.0/odoo/odoo/api.py", line 365, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/khkhkh/odoo/14.0/extra-addons/odoo-shopinvader/shopinvader_sale_update_price/models/shopinvader_backend.py", line 51, in launch_sale_price_update
    sale_carts = self.env["sale.order"].search(domain)
  File "/home/khkhkh/odoo/14.0/odoo/odoo/models.py", line 1708, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/khkhkh/odoo/14.0/odoo/odoo/models.py", line 4489, in _search
    if expression.is_false(self, args):
  File "/home/khkhkh/odoo/14.0/odoo/odoo/osv/expression.py", line 229, in is_false
    elif token[1] == 'in' and not (isinstance(token[2], Query) or token[2]):
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/khkhkh/odoo/14.0/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/khkhkh/odoo/14.0/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: 'int' object is not subscriptable

```

**Review by sebastienbeau — APPROVED** [review]
LGTM (code review)

**Comment by sebastienbeau** [comment]
@Cedric-Pigeon can you rebase

**Comment by sebastienbeau** [comment]
@acsonefho if you have time can you do the rebase ?

**Comment by acsonefho** [comment]
> @acsonefho if you have time can you do the rebase ?

Done too!

**Comment by sebastienbeau** [comment]
thanks /ocabot merge patch

**Pull request merged**
