### PR TITLE
[14.0][mig] shopinvader_locomotive_algolia

### PR DESCRIPTION
**Pull request by hparfr**
depends of https://github.com/shopinvader/odoo-shopinvader/pull/856

### CODE REVIEW

**Comment by hparfr** [comment]
~I will rebase it~ [edit] done ! [/edit]

**Comment by PierrickBrun** [comment]
@hparfr Can you redo the formatting commit ? I think pre-commit changed since then

**Comment by hparfr** [comment]
@PierrickBrun done

**Review by PierrickBrun — APPROVED** [review]

**Pull request merged**
