### PR TITLE
[10.0] shopinvader: improve shopinvader.partner views

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Review by Cedric-Pigeon — APPROVED** [review]

**Review by Cedric-Pigeon — CHANGES_REQUESTED** [review]
@alexis-via Could check why travis is red please?

**Review by sebastienbeau — APPROVED** [review]
I have rebased the PR, let's wait for travis and merge it

**Comment by sebastienbeau** [comment]
Re rebase with pep fix

**Comment by sebastienbeau** [comment]
rebase correctly done /ocabot merge minor

**Pull request merged**
