### PR TITLE
[16.0][IMP] shopinvader_api_customer:  add a hook to get customer values before update

### PR DESCRIPTION
**Pull request by benwillig**

### CODE REVIEW

**Review by lmignon — APPROVED** [review]

**Comment by paradoxxxzero** [comment]
@sbidoul is the git bot still broken?

**Comment by sbidoul** [comment]
@paradoxxxzero I think the bot is fine. The last merge attempt here had a genuine test failure.

**Comment by paradoxxxzero** [comment]
@sbidoul oh so we should merge these right?

**Pull request merged**
