### PR TITLE
[14.0][IMP] shopinvader: add index on company

### PR DESCRIPTION
**Pull request by acsonefho**
Add an index to fix a perf issue when many records.

### CODE REVIEW

**Review by simahawk — COMMENTED** [review]
sounds good but: build is red and - please - do not include odoo version in the commit msg :pray:

**Comment by acsonefho** [comment]
> sounds good but: build is red and - please - do not include odoo version in the commit msg pray

I'll do the rebase and change the commit message when this PR will be merged: https://github.com/shopinvader/odoo-shopinvader/pull/1317

**Review by hparfr — APPROVED** [review]

**Review by simahawk — APPROVED** [review]

**Comment by acsonefho** [comment]
@hparfr can you re-trigger the merge please?

**Pull request merged**
