### PR TITLE
[12.0][MIG] shopinvader

### PR DESCRIPTION
**Pull request by rousseldenis**
Depends on :

* [x] https://github.com/shopinvader/odoo-misc/pull/2
* [x] https://github.com/shopinvader/odoo-shopinvader/pull/318
* [x] https://github.com/OCA/server-tools/pull/1461
* [x] https://github.com/OCA/sale-workflow/pull/821
* [x] https://github.com/odoo/odoo/pull/33517

To fix:
* [x] opt_out field

To forward port:
* [x] https://github.com/shopinvader/odoo-shopinvader/pull/324/ 

Before merge : 

* [x] Remove entry in oca_dependencies.txt

### CODE REVIEW

**Comment by rousseldenis** [comment]
@shopinvader Odoo removed the opt_out field from res.partner (and from mail module).

It is located now on each mailing list.

We have to decide what to do with that field.

**Comment by rousseldenis** [comment]
> @shopinvader Odoo removed the opt_out field from res.partner (and from mail module).
> 
> It is located now on each mailing list.
> 
> We have to decide what to do with that field.

There is another computed field 'is_blacklisted' on res.partner.

**Comment by rousseldenis** [comment]
Currently fixing tests

**Comment by lmignon** [comment]
@rousseldenis  OCA/sale-workflow#821 is merged :tada:

**Review by lmignon — APPROVED** [review]

**Pull request merged**
