### PR TITLE
[14.0][IMP] Switch to OCA copier

### PR DESCRIPTION
**Pull request by simahawk**
Testing an update of #1311

### CODE REVIEW

**Comment by simahawk** [comment]
@rousseldenis I disabled the check of the dev status, we should probably drop the commit 

[[IMP] shopinvader*: Align development statuses](https://github.com/shopinvader/odoo-shopinvader/pull/1352/commits/b11b9eba1d973accb918c6fb173c604012cb96bb)

WDYT?

**Comment by simahawk** [comment]
As the issue on https://github.com/shopinvader/locomotivecms-python-client/issues/5 persists I'd temporarily disable the check on unreleased deps

**Comment by simahawk** [comment]
I'll create an issue to revert [CI: temporarily disable unreleased-deps check](https://github.com/shopinvader/odoo-shopinvader/pull/1352/commits/1e6040c4a6b6c916dc1d88f282514ec2de32cbb9)

**Comment by simahawk** [comment]
> @rousseldenis I disabled the check of the dev status, we should probably drop the commit
> 
> [[IMP] shopinvader*: Align development statuses](https://github.com/shopinvader/odoo-shopinvader/pull/1352/commits/b11b9eba1d973accb918c6fb173c604012cb96bb)
> 
> WDYT?

I dropped the commit. We can rescue it later if needed.

**Comment by simahawk** [comment]
Forgive me if I fast track this but I'd like to see 14.0 green to unstuck PRs.
I'm available for fixes if you find something wrong.

/ocabot merge patch

**Comment by simahawk** [comment]
> @simahawk The merge process could not start, because command `git fetch origin pull/1352/head:tmp-pr-1352` failed with output:
> 
> ```
> fatal: unable to access 'https://github.com/shopinvader/odoo-shopinvader/': Failed to connect to github.com port 443: Connection refused
> ```

WHAAAT? :thinking:

**Comment by sbidoul** [comment]
:rofl: must be a transient, please try again

**Comment by simahawk** [comment]
Maybe the bot thinks is still 1st of April :smile: 

/ocabot merge patch

**Comment by simahawk** [comment]
> refusing to allow a Personal Access Token to create or update workflow `.github/workflows/pre-commit.yml` without `workflow` scope

checking...

**Comment by simahawk** [comment]
@sbidoul shall we tweak something on access toke settings? https://docs.github.com/en/organizations/managing-programmatic-access-to-your-organization/setting-a-personal-access-token-policy-for-your-organization

**Comment by sbidoul** [comment]
I'm always prudent with giving permissions to a bot to modify automations. Alright there is no risk that the OCA GitHub bot would become sentient but still :) Let me merge this manually.

**Pull request merged**
