### PR TITLE
[16.0] [IMP] shopinvader_api_cart: Allow to modify the commitment date

### PR DESCRIPTION
**Pull request by ivantodorovich**
Allow to modify the cart's commitment date

### CODE REVIEW

**Review by santostelmo — APPROVED** [review]

**Review by simahawk — APPROVED** [review]

**Comment by simahawk** [comment]
@lmignon good for you?

**Review by lmignon — APPROVED** [review]

**Review by lmignon — COMMENTED** [review]
Are you sure you want to update the commitment_date as a normal field? Seems strange to me... This date is the date promised TO the customer. IMO it's not the one requested by the user. It therefore could depend on a a lot of organisational constrains.

**Review by lmignon — CHANGES_REQUESTED** [review]
Question in my previous comment.

**Comment by ivantodorovich** [comment]
Thanks for you review and your comments, @lmignon !

Sorry for not replying sooner, I really wanted to check with our functional colleagues before answering here.

You are certainly right. In our project, we will rely on automated rules and constraints.. so we will let the customer choose the delivery date (`commitment_date` field). However, without them, it makes no sense to expose this field.. so we shouldn't do it in shopinvader core

I'll close it. Many thanks!

**Comment by lmignon** [comment]
@ivantodorovich You're welcome ;-)

**Pull request closed without merging**
