### PR TITLE
[12][IMP] add test to create shopinvader category from category

### PR DESCRIPTION
**Pull request by lmignon**
This PR is a forward port of the tests into #419 to see if the problem is also present into 12.0

### CODE REVIEW

**Comment by sebastienbeau** [comment]
I am going to rebase it

**Comment by sebastienbeau** [comment]
I just create a new PR here rebased : https://github.com/shopinvader/odoo-shopinvader/pull/927
Let's see if still red, if it's the case I will fix it

**Review by PierrickBrun — APPROVED** [review]

**Review by PierrickBrun — CHANGES_REQUESTED** [review]
Approved by error, the PR has been re done by Sebastien

**Comment by sebastienbeau** [comment]
I close this one.
The code in now fixed on V12 but I merge the test to avoid getting back this issue

**Pull request closed without merging**
