### PR TITLE
13.0 Migrate shopinvader_lead

### PR DESCRIPTION
**Pull request by gurneyalex**

### CODE REVIEW

**Review by simahawk — APPROVED** [review]
NOTE: there's no default template for the email notification as the ones provided are only for demo.
Would you mind adding a default one instead?
Somehow related to this https://github.com/shopinvader/odoo-shopinvader/pull/544

BTW I wish we had something in odoo modules to load features like you can do w/ pythong pkgs (eg: pkgname[featurex]) that would allow to load certain data only if needed.

**Review by Cedric-Pigeon — APPROVED** [review]

**Comment by sebastienbeau** [comment]
@gurneyalex it's a pleasure to see you here ;)

**Comment by sbidoul** [comment]
I upgraded the bot so it's the same version as OCA's

**Pull request merged**
