### PR TITLE
[14.0][MIG] shopinvader_promotion_rule from 13.0

### PR DESCRIPTION
**Pull request by acsonefho**
Migration of `shopinvader_promotion_rule` from https://github.com/shopinvader/odoo-shopinvader/pull/894 (`13.0`)

Depends on
- [ ] https://github.com/OCA/sale-workflow/pull/1583

Remove:
- [ ] Entry in test-requirements

### CODE REVIEW

**Comment by rousseldenis** [comment]
@acsonefho Could you just add a technical commit with entry in test-requirements.txt in order to get tests greenify ?

**Comment by acsonefho** [comment]
@shopinvader/shopinvader-maintainers Can you review and merge please?

**Comment by sebastienbeau** [comment]
@acsonefho @acsonefho I am ok to merge this but we should just fix the typo (in french) in the dependency module : https://github.com/OCA/sale-workflow/pull/1583#discussion_r636339136

**Comment by sebastienbeau** [comment]
@acsonefho Can tout remove the change test-requirement as dependency have been merged?
Thanks

**Comment by acsonefho** [comment]
> @acsonefho Can tout remove the change test-requirement as dependency have been merged? Thanks

Done

**Pull request merged**
