### PR TITLE
[13.0] Add shopinvader_delivery_state

### PR DESCRIPTION
**Pull request by simahawk**
- [x] depends on https://github.com/OCA/sale-workflow/pull/1649

Addresses https://github.com/shopinvader/odoo-shopinvader/issues/993

### CODE REVIEW

**Review by ivantodorovich — APPROVED** [review]

**Review by mmequignon — APPROVED** [review]

**Comment by simahawk** [comment]
dammit, I merged w/ nobump and the module is not available.
@sbidoul any way to force publishing or OCA modules to pypi?

**Comment by sbidoul** [comment]
It is on PyPI:

image

I'm restarting the job.

**Comment by sbidoul** [comment]
@simahawk Installation went though this time. I guess you need to give it a few minutes to appear on PyPI ?

**Comment by simahawk** [comment]
@sbidoul merci. I've been impatient :rofl:

**Pull request merged**
