### PR TITLE
[13.0][MIG] shopinvader_elasticsearch

### PR DESCRIPTION
**Pull request by rousseldenis**
Includes:

* [x] #506 

Depends on :

* [x] https://github.com/OCA/search-engine/pull/43

### CODE REVIEW

**Comment by simahawk** [comment]
@rousseldenis looks good but build is red:

```
module shopinvader_elasticsearch: Unmet dependencies: connector_elasticsearch
```

**Comment by rousseldenis** [comment]
> @rousseldenis looks good but build is red:
> 
> ```
> module shopinvader_elasticsearch: Unmet dependencies: connector_elasticsearch
> ```

https://github.com/OCA/search-engine/pull/43

Reveiws are welcome ! :smiley:

**Comment by simahawk** [comment]
ìt's merging :wink:

**Review by lmignon — APPROVED** [review]

**Review by simahawk — APPROVED** [review]

**Pull request merged**
