### PR TITLE
[MIG] shopinvader_notification_default: Migration to 14.0

### PR DESCRIPTION
**Pull request by chafique-delli**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@chafique-delli Could you rebase ?

**Review by Cedric-Pigeon — APPROVED** [review]
code review only

**Review by kevinkhao — APPROVED** [review]
code review LGTM

**Comment by simahawk** [comment]
merged via https://github.com/shopinvader/odoo-shopinvader/pull/969

**Pull request closed without merging**
