### PR TITLE
[14.0][IMP] shopinvader_locomotive: add id for country's states

### PR DESCRIPTION
**Pull request by acsonefho**
Sometimes the front-side need the `id` of states (to create customer for example).
So add the `id` into the parser.

### CODE REVIEW

**Review by lmignon — CHANGES_REQUESTED** [review]
@acsonefho Can you fix the pre-commit and ping me once it's done so we can merge this one.

**Comment by acsonefho** [comment]
@shopinvader/shopinvader-maintainers

**Review by PierrickBrun — APPROVED** [review]
LGTM

**Comment by acsonefho** [comment]
@shopinvader/shopinvader-maintainers Can you review and merge please?

**Review by florian-dacosta — APPROVED** [review]
LGTM code review

**Comment by acsonefho** [comment]
@PierrickBrun I create this PR https://github.com/OCA/queue/pull/440 who fix an issue into `queue` mais I'm not sure if this is a good solution.
Because the error to merge happens for every PR (or rebase) for `v14.0`

Maybe there is something strange about `queue jobs` into a shopinvader module.

**Review by sebastienbeau — APPROVED** [review]
LGTM (code review)

Can you rebase to make it green ?

**Pull request merged**
