### PR TITLE
[14.0][IMP] shopinvader_(search_engine): Improve ux

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
CC @hparfr 

https://github.com/shopinvader/odoo-shopinvader/discussions/1295

### CODE REVIEW

**Review by hparfr — APPROVED** [review]
LGTM

**Comment by hparfr** [comment]
Test fails. Don't know why.

**Review by acsonefho — APPROVED** [review]

**Comment by acsonefho** [comment]
> Test fails. Don't know why.

I think job failed due to this: https://github.com/OCA/queue/pull/440

**Review by simahawk — APPROVED** [review]

**Pull request merged**
