### PR TITLE
[13.0][FWD] #449 shopinvader: force update pricelist and prices

### PR DESCRIPTION
**Pull request by rousseldenis**
Depends on:

* [ ] https://github.com/OCA/sale-workflow/pull/1155

### CODE REVIEW

**Review by simahawk — CHANGES_REQUESTED** [review]
IMO this should stay in a new module, something like `shopinvader_sale_update_price` or similar

**Comment by rousseldenis** [comment]
> IMO this should stay in a new module, something like `shopinvader_sale_update_price` or similar

Makes sense indeed.

**Comment by sebastienbeau** [comment]
@rousseldenis seem that the PR on dependency is still not merge.
As in V14 the price recoputation is native https://github.com/odoo/odoo/blob/14.0/addons/sale/models/sale.py#L454
What do you think about not doing this in V13 and focus in V14 ?

**Comment by Cedric-Pigeon** [comment]
@sebastienbeau Just implemented the feature in a dedicated addon in V14  #1076

**Pull request closed without merging**
