### PR TITLE
[14.0][ADD] shopinvader_l10n_fr

### PR DESCRIPTION
**Pull request by ivantodorovich**
New module to implement `l10n_fr` for shopinvader.

* Expose `siret` fields on address and customer services.

### CODE REVIEW

**Comment by simahawk** [comment]
Tests are :red_circle: . As you are there, can you turn off logging of requests for vcr.py on elasticsearch tests?

**Comment by ivantodorovich** [comment]
So, tests are red becase installing `l10n_fr` coa breaks everything up. I guess this is normal, tests are meant to run without localizations installed.

As for how to solve it, I tried to set it as a rebel module but it seems `manifestoo -d . check-licenses` doesn't like that.

I'm wondering:
- Does it make sense that we merge this module here? I don't expect we'll have much shopinvader-l10n modules but maybe we need separate localization based repositories for them, like we have in OCA?
- In any case, @sbidoul any idea what's going on with manifestoo here? It seems not to like rebel modules

**Comment by sbidoul** [comment]
> what's going on with manifestoo here? It seems not to like rebel modules

I suppose we need to pass INCLUDE and EXCLUDE the license and dev status checks.
The [docs for the select options is here](https://manifestoo.readthedocs.io/en/latest/addons_selection.html). That will need to be done in the OCA template too.

**Comment by sbidoul** [comment]
Or maybe we should put the license and dev status checks in separate jobs.

**Comment by ivantodorovich** [comment]
Thanks @sbidoul 

This seems to work. I don't really like the multi line script though.

```yaml
- name: Check licenses
  run: |
    if [ -n "$INCLUDE" ]
    then manifestoo --select-include "$INCLUDE" check-licenses
    else manifestoo -d . --select-exclude "$EXCLUDE" check-licenses
    fi

- name: Check development status
  run: |
    if [ -n "$INCLUDE" ]
    then manifestoo --select-include "$INCLUDE" check-dev-status --default-dev-status=Beta
    else manifestoo -d . --select-exclude "$EXCLUDE" check-dev-status --default-dev-status=Beta
    fi
```

Maybe we could do this in [oca-ci](https://github.com/OCA/oca-ci) with a `oca_run_manifestoo` bin, to keep the github action cleaner.

Then it'd be like this:

```yaml
- name: Check licenses
  run: oca_run_manifestoo check-licenses
- name: Check development status
  run: oca_run_manifestoo check-dev-status --default-dev-status=Beta
```

What do you think?

**Comment by simahawk** [comment]
@ivantodorovich what's next?

**Comment by ivantodorovich** [comment]
> @ivantodorovich what's next?

I'd go for adding a `oca_run_manifestoo` bin in `oca-ci` image, as mentioned here: https://github.com/shopinvader/odoo-shopinvader/pull/1223#issuecomment-1028332582

Then we could change the repo templates to use it

Would you be ok with it @sbidoul ?

**Comment by sbidoul** [comment]
This was resolved in https://github.com/OCA/oca-ci/pull/24 and https://github.com/OCA/oca-ci/pull/25. It should be green now.

**Comment by ivantodorovich** [comment]
Cool! Let's see if it passes🤞🏻

**Comment by ivantodorovich** [comment]
Yay! it's green 🍏 
thanks a lot @sbidoul !

**Comment by sebastienbeau** [comment]
LGTM (code review) /ocabot merge patch

**Comment by sebastienbeau** [comment]
@ivantodorovich Can you rebase so I can merge it

**Comment by ivantodorovich** [comment]
This is ready @sebastienbeau

**Comment by sebastienbeau** [comment]
/ocabot merge patch

Thanks

**Comment by ivantodorovich** [comment]
FTR the issue seems to be related to the permissions given on the bot's github token

**Pull request closed without merging**
