### PR TITLE
[12.0] modernize CI

### PR DESCRIPTION
**Pull request by sbidoul**
Same as #589

### CODE REVIEW

**Comment by sbidoul** [comment]
This one is [failing](https://travis-ci.com/github/acsone/odoo-shopinvader/jobs/299822195?utm_medium=notification&utm_source=email) because `shopinvader_product_stock` tries to import `JobMixin` from `odoo.addons.queue.tests.common` and that class does not exist anymore.

**Comment by rousseldenis** [comment]
> This one is [failing](https://travis-ci.com/github/acsone/odoo-shopinvader/jobs/299822195?utm_medium=notification&utm_source=email) because `shopinvader_product_stock` tries to import `JobMixin` from `odoo.addons.queue.tests.common` and that class does not exist anymore.

We'll try to merge this https://github.com/OCA/queue/pull/150

**Comment by sbidoul** [comment]
Here you can see how to [use an addon from an unmerged PR](https://github.com/acsone/odoo-shopinvader/commit/aee38309dabfba464f4b4c76621564905a7cb91b).

**Comment by rousseldenis** [comment]
> Here you can see how to [use an addon from an unmerged PR](https://github.com/acsone/odoo-shopinvader/commit/1f3c49286f2541c2d531382efd4fa991683b78c7).

Is the 'test-requirements.txt' mechanism new or I felt asleep too much these times ? :smile:

**Comment by sbidoul** [comment]
> Is the 'test-requirements.txt' mechanism new

Yes it's new. When you have `MQT_DEP=PIP`, mqt [installs all dependencies with pip](https://github.com/OCA/maintainer-quality-tools/blob/6d68bedc70cf981f8e177ff57b944b53f585def0/travis/travis_install_nightly#L121-L132).

It's much more robust because:
- no use of redundant files `oca_dependencies.txt` and `requirements.txt` (all dependencies are declared in manifests and setup.py anyway)
- no installations of dependencies we don't need, which mean less breakage due to dependent repos

**Comment by rousseldenis** [comment]
What is (would be) OCA guideline with that ?

**Comment by sbidoul** [comment]
> What is (would be) OCA guideline with that ?

I've not communicated on OCA side. Let's say if people see issues with dependencies they can try setting `MQT_DEP=PIP` in `.travis.yml` to enable the new installation mechanism.

**Review by sebastienbeau — APPROVED** [review]
\o/

**Pull request merged**
