### PR TITLE
10.0 FIX travis: limit test to maintained version, OCB

### PR DESCRIPTION
**Pull request by bealdav**
For environmental considerations and quick execution

### CODE REVIEW

**Comment by bealdav** [comment]
cc @sebastienbeau @rousseldenis @Cedric-Pigeon @PierrickBrun @hparfr

**Comment by bealdav** [comment]
Some of the commits are also here https://github.com/shopinvader/odoo-shopinvader/pull/842

**Review by Cedric-Pigeon — APPROVED** [review]

**Review by PierrickBrun — APPROVED** [review]
Thanks

**Review by hparfr — APPROVED** [review]

**Comment by bealdav** [comment]
Hi @Cedric-Pigeon thanks to have reviewed this PR.
I think you're PSC here ? If yes, could you merge ? 
Fast merge because old version ;-)

**Pull request merged**
