### PR TITLE
[10.0][FIX] fix database transaction error on multi-languages anonymous carts

### PR DESCRIPTION
**Pull request by Cedric-Pigeon**
Related on https://github.com/shopinvader/odoo-shopinvader/pull/341

The patch merged in the previous PR reaches its limits while a lot of visitors adds to cart at the same time.
It leads to transaction error on database because they are trying to update the anonymous partner at the same time.
As the only field impacted by the language is `sale_order_line.name`, I suggest being only focused on this one.

### CODE REVIEW

**Comment by sebastienbeau** [comment]
LGTM (code review)

**Review by sebastienbeau — APPROVED** [review]
LGTM (code review)
Just need to check way travis in red

**Review by lmignon — APPROVED** [review]
LGTM, a lot more easier and readable (Code review only)

**Pull request merged**
