### PR TITLE
[10.0][FIX] pylint configuration for mandatory checks

### PR DESCRIPTION
**Pull request by rousseldenis**
Remove unused rule that triggers randomly

See failed pylint job: https://travis-ci.org/github/shopinvader/odoo-shopinvader/jobs/683813673

https://github.com/OCA/pylint-odoo/issues/282

### CODE REVIEW

**Comment by rousseldenis** [comment]
@sbidoul @lmignon

**Review by sbidoul — APPROVED** [review]
Fine with me. This check is not really useful IMO.

Can you add a link to the failed travis job? And create an issue on https://github.com/OCA/pylint-odoo?

Also, when this is merged, this needs to be ported to all branches and shopinvader repos.

**Review by lmignon — APPROVED** [review]

**Review by baimont — APPROVED** [review]

**Pull request merged**
