### PR TITLE
[14.0][MIG] shopinvader_pos from 10.0

### PR DESCRIPTION
**Pull request by acsonefho**
Migration of `shopinvader_pos` from https://github.com/shopinvader/odoo-shopinvader/pull/987 (`10.0`)

### CODE REVIEW

**Comment by rousseldenis** [comment]
@acsonefho Could you check why Travis is red ?

**Review by rousseldenis — APPROVED** [review]

**Review by sebastienbeau — APPROVED** [review]
LGTM code review

**Pull request merged**
