### PR TITLE
[MIG] shopinvader_customer_multi_user: Migration to 14.0

### PR DESCRIPTION
**Pull request by chafique-delli**

### CODE REVIEW

**Review by PierrickBrun — APPROVED** [review]

**Review by acsonefho — APPROVED** [review]
Code LGTM

**Review by rousseldenis — APPROVED** [review]

**Comment by sbidoul** [comment]
This error was fixed in v13: https://github.com/shopinvader/odoo-shopinvader/commit/327ec81178d27ee571498c55d5c7cc9876a4bfe4

**Review by mourad-ehm — APPROVED** [review]

**Comment by rousseldenis** [comment]
@simahawk Keep the fix commit or squash ?

**Pull request merged**
