### PR TITLE
[14.0][MIG] shopinvader_sale_packaging

### PR DESCRIPTION
**Pull request by kevinkhao**
Cleanup of https://github.com/shopinvader/odoo-shopinvader/pull/873 
Started from 14.0, cherry-picked @simahawk 's listed commits, resolved conflicts, cherry-picked migration commit
I am still verifying I did not butcher any commit

### CODE REVIEW

**Comment by kevinkhao** [comment]
should be good to go

**Comment by sebastienbeau** [comment]
@simahawk @hparfr can you have a review?

**Comment by simahawk** [comment]
LG but you should drop the migration scripts ;)

**Comment by kevinkhao** [comment]
done

**Review by simahawk — APPROVED** [review]

**Comment by kevinkhao** [comment]
here: https://github.com/shopinvader/odoo-shopinvader/pull/903

I get:

ERROR: Could not find a version that satisfies the requirement odoo14-addon-shopinvader_sale_packaging (from versions: none)
ERROR: No matching distribution found for odoo14-addon-shopinvader_sale_packaging

shouldn't this module already be published since it's merged ?

**Pull request merged**
