### PR TITLE
10.0 BACKPORT invader_partner_firstname

### PR DESCRIPTION
**Pull request by bealdav**

### CODE REVIEW

**Review by PierrickBrun — APPROVED** [review]
A bit concerned by the double travis run, but I think this is not so much of a problem since there is not a lot of activity in v10

**Comment by bealdav** [comment]
I'm open to any other test plan

**Review by mourad-ehm — APPROVED** [review]
Code review

**Comment by sebastienbeau** [comment]
@bealdav need a rebased

**Comment by bealdav** [comment]
Travis fails crying
```
ERROR: Could not find a version that satisfies the requirement odoo10-addon-base_sparse_field_list_support (from odoo10-addon-shopinvader->-r test-requirements.txt (line 14)) (from versions: none)

ERROR: No matching distribution found for odoo10-addon-base_sparse_field_list_support (from odoo10-addon-shopinvader->-r test-requirements.txt (line 14))
```

But here https://pypi.org/project/odoo10-addon-base-sparse-field-list-support

Not sure to understand

Is the problem comes from _ instead of -  ?!

**Comment by bealdav** [comment]
Please @sbidoul do you know if it comes from recent actions on dotfiles or OCA pip addons evolution ? cc @rousseldenis

**Comment by sbidoul** [comment]
We should not have travis here anymore. Please remove `.travis.yml` from the branch.

**Comment by sbidoul** [comment]
And the reason why travis complains is that MQT now uses an index that has OCA addons only. And base_sparse_field_list_support is a shopinvader addon, not OCA. The GitHub action has an [extra index](https://github.com/shopinvader/odoo-shopinvader/blob/f9905dd07fe16b0406bee6a2a6d77e43ae104224/.github/workflows/test.yml#L32) with the shopinvader addons.

**Comment by bealdav** [comment]
Thanks a lot

**Comment by sebastienbeau** [comment]
@bealdav can you fix the test please ?

**Comment by lmignon** [comment]
Closing since 10.0 is no more actively maintained.

**Pull request closed without merging**
