### PR TITLE
shopinvader: fix test_invoice

### PR DESCRIPTION
**Pull request by simahawk**
~A test is failing in all latest PRs. TO BE CHECKED.~

This commit odoo/odoo@71b8269
introduced a check on move state. Make the build happy w/ it.

### CODE REVIEW

**Comment by simahawk** [comment]
So, tests on 13.0 are broken due to https://github.com/shopinvader/odoo-shopinvader/pull/943/checks?check_run_id=2349865586#step:6:301

**Comment by HviorForgeFlow** [comment]
AFAICS it seems that invoice is trying to be posted twice. Checking if invoice (account.move) is posted and not post it on _make_payment would do the fix. My question is, why it wasn't failing before ... maybe there is another reason.

**Comment by simahawk** [comment]
> AFAICS it seems that invoice is trying to be posted twice. Checking if invoice (account.move) is posted and not post it on _make_payment would do the fix. My question is, why it wasn't failing before ... maybe there is another reason.

yes. The only thing I could think of till now is that something has changed in core odoo. BUT I did not have time to look better into it. I'll check later. If you have some good pointers, let me know ;)

**Comment by simahawk** [comment]
@HviorForgeFlow there you go https://github.com/odoo/odoo/commit/71b82693bb6d

**Review by HviorForgeFlow — APPROVED** [review]
:+1:

**Comment by simahawk** [comment]
@sbidoul could you check what's going on here? https://github.com/shopinvader/odoo-shopinvader/runs/2398448290?check_suite_focus=true

Tests pass but on the second test action `oca_export_and_commit_pot` fails.

**Comment by sbidoul** [comment]
Looks like the git push fails [here](https://github.com/shopinvader/odoo-shopinvader/blob/4624d2b2ec73b7c5f40d047e9dc6bd00b771947a/.github/workflows/test.yml#L43): `shallow update not allowed`

image

**Comment by simahawk** [comment]
yes, but why? This PR is not different from previous ones, no?
Is there anything I can do on my side?
I don't see any particular setting for checkout depth or anything related to "unshallow stuff".
Am I missing anything?

**Comment by sbidoul** [comment]
If only I knew... 

Could you try adding `git fetch --unshallow --all` just before the git push ?

**Comment by simahawk** [comment]
@sbidoul seems it worked, at least here... but here was already green :sweat_smile:

**Comment by sbidoul** [comment]
> but here was already green

Nope, .pot generation is only done on ocabot merge. So we'll see.

**Comment by simahawk** [comment]
@sbidoul :tada: :pray:

**Comment by sbidoul** [comment]
Con piacere. Now this needs to go to https://github.com/shopinvader/shopinvader-addons-repo-template

**Pull request merged**
