### PR TITLE
[10.0][FIX] Fix delete synchronisation

### PR DESCRIPTION
**Pull request by sebastienbeau**
When deleting template, product, binding we should be sure to call
unlink code of the binding in order to have the synchronisation working
Deleting with casade in postgres bypass the ORM

### CODE REVIEW

**Comment by rousseldenis** [comment]
@sebastienbeau IMHO this code should be in 'shopinvader' module as no code depends on shopinvader_search_engine.

**Review by lmignon — CHANGES_REQUESTED** [review]
@sebastienbeau I share the same opinion as @rousseldenis

**Comment by sebastienbeau** [comment]
You are totally right ! I will fix it

**Comment by rousseldenis** [comment]
@sebastienbeau

**Comment by rousseldenis** [comment]
@sebastienbeau

**Comment by rousseldenis** [comment]
@sebastienbeau

**Comment by sebastienbeau** [comment]
I am working on it

**Comment by sebastienbeau** [comment]
I have refactored my code.
Note the constraint on deleting is raise by the search_engine module.
So I keep my test in shopinvader_search_engine see here: https://github.com/OCA/search-engine/blob/12.0/connector_search_engine/models/se_binding.py#L63

**Comment by sebastienbeau** [comment]
@rousseldenis @lmignon PR is ready now

**Comment by sebastienbeau** [comment]
ping @rousseldenis

**Review by rousseldenis — APPROVED** [review]
LGTM

**Pull request merged**
