### PR TITLE
[14.0][FWP] Make difference between update done by customer and done by Odoo's interface

### PR DESCRIPTION
**Pull request by acsonefho**
Forward-Port of https://github.com/shopinvader/odoo-shopinvader/pull/596

### CODE REVIEW

**Comment by rousseldenis** [comment]
@acsonefho Could you check pre-commit and tests?

**Comment by acsonefho** [comment]
> @acsonefho Could you check pre-commit and tests?

@rousseldenis Like always, tests are red but not related to this PR.

**Comment by rousseldenis** [comment]
@acsonefho 14.0 branch is green... at least check if you are based on the last commit of 14.0

Your pre-commit is red.

**Comment by simahawk** [comment]
FYI here is the problem https://github.com/shopinvader/odoo-shopinvader/pull/1148#issuecomment-950692462

**Review by Cedric-Pigeon — APPROVED** [review]

**Review by florian-dacosta — APPROVED** [review]
LGTM

**Comment by sebastienbeau** [comment]
can you rebase @acsonefho

**Comment by acsonefho** [comment]
> can you rebase @acsonefho

Done :)

**Pull request merged**
