### PR TITLE
[14.0][IMP] shopinvader_invoice: Restore service definition

### PR DESCRIPTION
**Pull request by rousseldenis**
Even if the account.move state values changed, we must return the former
values as service should not change.

### CODE REVIEW

**Comment by rousseldenis** [comment]
Need to update service output docs

**Comment by rousseldenis** [comment]
@acsonefho @hparfr @david-popa As you were involved in migration PR.

**Review by hparfr — APPROVED** [review]
LGTM

**Review by acsonefho — APPROVED** [review]
Code LGTM

**Review by Cedric-Pigeon — APPROVED** [review]

**Comment by rousseldenis** [comment]
Waiting a little bit as payment states should have been set in 'state' too, to be logic with what we want to do here.

**Review by sebastienbeau — APPROVED** [review]
LGTM code review

**Review by lmignon — APPROVED** [review]

**Pull request merged**
