### PR TITLE
[16.0][FIX] CI

### PR DESCRIPTION
**Pull request by lmignon**
Fix breaking changes into dependencies:

* https://github.com/odoo/odoo/commit/65a19492a8044be4f05a8200a6956c3e50b69eab
* https://github.com/OCA/sale-workflow/pull/3009

### CODE REVIEW

**Comment by lmignon** [comment]
ping @sebastienbeau @simahawk @qgroulard This PR fixes the CI. Pay attention to the breaking changes into the [`sale_product_set`](https://github.com/OCA/sale-workflow/pull/3009) addon.

**Review by qgroulard — APPROVED** [review]
Thanks !

**Review by simahawk — APPROVED** [review]

**Review by sebastienbeau — APPROVED** [review]
LGTM (code review)

Thanks a lot Laurent for the fix !

**Pull request merged**
