### PR TITLE
[14.0][MIG] shopinvader_product_template_multi_link

### PR DESCRIPTION
**Pull request by acsonefho**
Migration of `shopinvader_product_template_multi_link` from `13.0`

### CODE REVIEW

**Comment by simahawk** [comment]
LG overall but I'm not sure that [s_product_template_multi_link: fix indexed ID](https://github.com/shopinvader/odoo-shopinvader/pull/1073/commits/ca54d1f0bf197c41dc8bfec689f6bda76b6d4a1d) is wanted here since [[REF] clean up mix with id and object id fix issue ](https://github.com/shopinvader/odoo-shopinvader/commit/9241c73d56cd3d5bb94624b945b5aa7e20515028) landed on 14.0.
Right @sebastienbeau ?

**Comment by sebastienbeau** [comment]
Indeed @acsonefho  you need to revert the commit 
ca54d1f

**Comment by sebastienbeau** [comment]
I have done the revert and fixed an issue with the data here: https://github.com/acsone/odoo-shopinvader/pull/4

**Comment by sebastienbeau** [comment]
@acsonefho can you merge it, in your PR

**Comment by sebastienbeau** [comment]
Also after merging it can you rebase the PR (to include this fix https://github.com/shopinvader/odoo-shopinvader/pull/1083 so the CI can be green)

**Review by sebastienbeau — APPROVED** [review]
LGTM code review and test

**Pull request merged**
