### PR TITLE
Install dependencies with pip

### PR DESCRIPTION
**Pull request by sbidoul**

### CODE REVIEW

**Comment by lmignon** [comment]
AFAIK addons of the shopinvader org are not published on pypi nor itno the OCA wheelhouse :-/

**Comment by lmignon** [comment]
@sbidoul It seems that the dependencies are still installed the old way 
image

**Comment by sbidoul** [comment]
> still installed the old way

yes, typo

> addons of the shopinvader org are not published on pypi nor itno the OCA wheelhouse

yes, but we can `--extra-index-url https://wheelhouse.shopinvader.com/simple/`

**Comment by sbidoul** [comment]
Hm @lmignon this repo uses a custom branch of MQT. That's why it does not pick-up the new `MQT_DEP` var.

**Comment by lmignon** [comment]
> Hm @lmignon this repo uses a custom branch of MQT. That's why it does not pick-up the new `MQT_DEP` var.

arghhhh! I don't know why but we should use MQT from OCA

**Comment by sbidoul** [comment]
superseded by #589 (for 10)

**Pull request closed without merging**
