### PR TITLE
[MIG] shopinvader_wishlist: Migration to 14.0 

### PR DESCRIPTION
**Pull request by simahawk**
Replaces #867

- [x] Depends on https://github.com/OCA/sale-workflow/pull/1596

### CODE REVIEW

**Comment by simahawk** [comment]
removed commit https://github.com/shopinvader/odoo-shopinvader/pull/972/commits/28dc139733ed4d2dd089a82808190b759b4ce35d and moved to #974

**Comment by simahawk** [comment]
note to myself: fwd port https://github.com/shopinvader/odoo-shopinvader/pull/982

**Comment by simahawk** [comment]
@sebastienbeau @PierrickBrun @hparfr can you review this?

**Review by hparfr — APPROVED** [review]
code review, lgtm

**Review by ivantodorovich — APPROVED** [review]

**Pull request merged**
